# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Publish Website

on: 
  workflow_dispatch:
  push:   

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [2.7]
    runs-on: ${{ matrix.os }}
  

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install Bundles
        run: bundle install


      - name: Build Website
        run: bundle exec rake build

      - name: Deploy Website to live via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          local_path: '_site/*'
          remote_path: '/var/www/eliatra.com/html/'
          sftp_only: true
          ssh_private_key: ${{ secrets.SFTP_SSH_PRIVATE_KEY }}
          sftpArgs: -C

      
      - name: Decache Cloudflare
        env:
          ELIATRA_CLOUDFLARE_ZONEID: ${{ secrets.ELIATRA_CLOUDFLARE_ZONEID }}
          ELIATRA_CLOUDFLARE_DECACHE_TOKEN: ${{ secrets.ELIATRA_CLOUDFLARE_DECACHE_TOKEN }}
        run: >-
          curl 
          -X POST "https://api.cloudflare.com/client/v4/zones/$ELIATRA_CLOUDFLARE_ZONEID/purge_cache" 
          -H "Authorization: Bearer $ELIATRA_CLOUDFLARE_DECACHE_TOKEN" 
          -H "Content-Type: application/json" 
          --data '{"purge_everything":true}'

